const surveyData = [
    {
        "vet_id": 1,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 1,
        "races_mixtes": 0,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 1
    },
    {
        "vet_id": 2,
        "wilaya": "Blida",
        "commune": "Mouzaia",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 2
    },
    {
        "vet_id": 3,
        "wilaya": "Blida",
        "commune": "Ouled Yaich",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 1,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 4,
        "wilaya": "Blida",
        "commune": "Boufarik",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 1,
        "avort_stade_variable": 0,
        "mortalite": 2
    },
    {
        "vet_id": 5,
        "wilaya": "Blida",
        "commune": "Boufarik",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 1,
        "production_mixte": 0,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 1
    },
    {
        "vet_id": 6,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 1,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 1,
        "avort_stade_fin": 0,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 7,
        "wilaya": "Blida",
        "commune": "Ouled Yaich",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 1,
        "production_lait": 0,
        "production_mixte": 0,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 2
    },
    {
        "vet_id": 8,
        "wilaya": "Blida",
        "commune": "Bougara",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 1,
        "avort_stade_fin": 1,
        "avort_stade_variable": 0,
        "mortalite": 3
    },
    {
        "vet_id": 9,
        "wilaya": "Blida",
        "commune": "Beni Tamou",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 0,
        "brucellose": 1,
        "danger_lait": 0,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 1
    },
    {
        "vet_id": 10,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 2
    },
    {
        "vet_id": 11,
        "wilaya": "Blida",
        "commune": "Soumaa",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 2
    },
    {
        "vet_id": 12,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 2
    },
    {
        "vet_id": 13,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 3
    },
    {
        "vet_id": 14,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 1,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 1,
        "avort_stade_fin": 0,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 15,
        "wilaya": "Blida",
        "commune": "Bouinan",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 1,
        "production_lait": 0,
        "production_mixte": 0,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 1,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 16,
        "wilaya": "Blida",
        "commune": "Bouinan",
        "races_locales": 1,
        "races_mixtes": 0,
        "races_etrangeres": 0,
        "production_viande": 1,
        "production_lait": 0,
        "production_mixte": 0,
        "mammites": 1,
        "brucellose": 1,
        "danger_lait": 1,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 1,
        "avort_stade_fin": 0,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 17,
        "wilaya": "Blida",
        "commune": "Mouzaia",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 1,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 0,
        "mortalite": 1
    },
    {
        "vet_id": 18,
        "wilaya": "Blida",
        "commune": "Bouinan",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 1
    },
    {
        "vet_id": 19,
        "wilaya": "Blida",
        "commune": "Blida",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 1,
        "avort_freq": 3,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 3
    },
    {
        "vet_id": 20,
        "wilaya": "Blida",
        "commune": "Boufarik",
        "races_locales": 0,
        "races_mixtes": 1,
        "races_etrangeres": 0,
        "production_viande": 0,
        "production_lait": 0,
        "production_mixte": 1,
        "mammites": 1,
        "brucellose": 0,
        "danger_lait": 0,
        "avort_freq": 2,
        "avort_stade_debut": 0,
        "avort_stade_milieu": 0,
        "avort_stade_fin": 0,
        "avort_stade_variable": 1,
        "mortalite": 3
    }
];
